//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Service.Helpers.Classes.MO_RequestResponse
{
    using System;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class MO_DataResponse
    {
        private string fullNameField { get; set; }
        private DateTime birthDateField { get; set; }
        private string locationsField { get; set; }
        private string educationInfoField { get; set; }
        private string spouseEducationInfoField { get; set; }
        private string workingActivityField { get; set; }
        private DateTime responseDateField { get; set; }


        /// <remarks/>
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        public DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        public string Locations
        {
            get
            {
                return this.locationsField;
            }
            set
            {
                this.locationsField = value;
            }
        }

        /// <remarks/>
        public string EducationInfo
        {
            get
            {
                return this.educationInfoField;
            }
            set
            {
                this.educationInfoField = value;
            }
        }

        /// <remarks/>
        public string SpouseEducationInfo
        {
            get
            {
                return this.spouseEducationInfoField;
            }
            set
            {
                this.spouseEducationInfoField = value;
            }
        }

        /// <remarks/>
        public string WorkingActivity
        {
            get
            {
                return this.workingActivityField;
            }
            set
            {
                this.workingActivityField = value;
            }
        }

        /// <remarks/>
        public DateTime ResponseDate
        {
            get
            {
                return this.responseDateField;
            }
            set
            {
                this.responseDateField = value;
            }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class MO_DataRequest
    {

        private string iinField;

        /// <remarks/>
        public string IIN
        {
            get
            {
                return this.iinField;
            }
            set
            {
                this.iinField = value;
            }
        }
    }
}